### NME 1 — Saturday, October 21st, 2023

# NumPy skill drill

The goal of this workbook is to practice the programming skills you'll need this semester. [NumPy](https://numpy.org/) is a commonly used Python package for working with data.

_**Note: this notebook is largely based off David Mimno and Allison Koenecke's 'NumPy Skill Drill' exercise from INFO 2950, FA22.**_

## Table of Contents

A. [Arrays](#A.-Arrays)

B. [Saving and loading arrays](#B.-Saving/loading-arrays)

C. [Indexing](#C.-Indexing)

D. [Operating on arrays](#D.-Operating-on-arrays)

E. [Avoiding for loops](#E.-Avoiding-for-loops)

Whenever you use NumPy, you first need to import it with the following line of code.

Run the following block of code by pressing the `ctrl` and `enter` keys simultaneously. This is the general keyboard shortcut for running a block of code in a notebook like this.

In [ ]:
import numpy as np

## A. Arrays

### Goal: Print an array.

The basic datatype in NumPy is an *array*, also called an *ndarray*. You can think of an array as a list of numbers. A basic way to create an array is to pass a Python list to the [`np.array()` function](https://numpy.org/doc/stable/reference/generated/numpy.array.html).

Python's `print()` function displays the value of a variable.


<span style="color:blue">**Exercise A1.**</span>

**Input**: an array with integers in increasing order.

```
[0 1 2 3 4 5 6 7]
```
 
**Output**: Print the array.

```
[0 1 2 3 4 5 6 7]
```


In [ ]:
# Given code
A = np.array([0, 1, 2, 3, 4, 5, 6, 7])

# your code here


----
<span style="color:blue">**Exercise A2.**</span>

**Input**: a 1x8 array with integers in increasing order.

```
[[0 1 2 3 4 5 6 7]]
```
 
**Output**: Print the array.

```
[[0 1 2 3 4 5 6 7]]
```


In [ ]:
# Given code
A = np.array([[0, 1, 2, 3, 4, 5, 6, 7]])

# your code here


----
<span style="color:blue">**Exercise A3.**</span>

**Input**: an 8x1 array with integers in increasing order.

```
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
```
 
**Output**: Print the array.

```
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
```


In [ ]:
# Given code
A = np.array([[0],
              [1],
              [2],
              [3],
              [4],
              [5],
              [6],
              [7]])

# your code here


----
### Goal: Access the number of dimensions of an array.

Arrays have *axes*, also called *dimensions*. A Python list has one dimension; you can specify an element of a list with one index number. A matrix has two dimensions because in order to specify an element of a matrix, you need two numbers. The numbers specify the row and column.


<span style="color:blue">**Exercise A4.**</span>

**Input**: an array with one axis/dimension with integers in increasing order.

```
[0 1 2 3 4 5 6 7]
```

**Output**: Print the number of dimensions of the array using the array's [`.ndim` attribute](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.ndim.html).

```
1
```


In [ ]:
# Given code
A = np.array([0, 1, 2, 3, 4, 5, 6, 7])

# your code here


----
<span style="color:blue">**Exercise A5.**</span>

**Input**: a 2d array with integers in increasing order.

```
[[0 1 2 3 4 5 6 7]]
```
 
**Output**: Print the number of dimensions of the array.

```
2
```


In [ ]:
# Given code
A = np.array([[0, 1, 2, 3, 4, 5, 6, 7]])

# your code here


----
<span style="color:blue">**Exercise A6.**</span>

**Input**: a 2d array with integers in increasing order.

```
[[0 1 2 3]
 [4 5 6 7]]
```
 
**Output**: Print the number of dimensions of the array.

```
2
```


In [ ]:
# Given code
A = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7]])

# your code here


----
<span style="color:blue">**Exercise A7.**</span>

**Input**: None.

 
**Output**: Use the [`np.array()` function](https://numpy.org/doc/stable/reference/generated/numpy.array.html#numpy.array) to create an array with three axes/dimensions. Print the number of dimensions of the array.

```
3
```


In [ ]:
# your code here


----
### Goal: Get the shape of an array.

An array's *shape* is a tuple representing the size of each dimension of an array. For a 2d array, the elements of the tuple correspond to height and width.


<span style="color:blue">**Exercise A8.**</span>

**Input**: an array with integers in increasing order.

```
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
```
 
**Output**: Print the shape of the array using the array's [`.shape` attribute](https://numpy.org/doc/stable/reference/generated/numpy.shape.html).

```
(2, 8)
```


In [ ]:
# Given code
A = np.array([[ 0,  1,  2,  3,  4,  5,  6,  7],
              [ 8,  9, 10, 11, 12, 13, 14, 15]])

# your code here


<span style="color:blue">**Exercise A9.**</span>

**Input**: a 1d array with integers in increasing order.

```
[0 1 2 3 4 5 6 7]
```
 
**Output**: Print the shape of the array.

```
(8,)
```


In [ ]:
# Given code
A = np.array([0, 1, 2, 3, 4, 5, 6, 7])

# your code here


----
<span style="color:blue">**Exercise A10.**</span>

**Input**: a 2d array with integers in increasing order.

```
[[0 1 2 3 4 5 6 7]]
```
 
**Output**: Print the shape of the array.

```
(1, 8)
```


In [ ]:
# Given code
A = np.array([[0, 1, 2, 3, 4, 5, 6, 7]])

# your code here


----
<span style="color:blue">**Exercise A11.**</span>

**Input**: a 2d array with integers in increasing order.

```
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
```
 
**Output**: Print the shape of the array.

```
(8, 1)
```


In [ ]:
# Given code
A = np.array([[0],
              [1],
              [2],
              [3],
              [4],
              [5],
              [6],
              [7]])

# your code here


----
<span style="color:blue">**Exercise A12.**</span>

**Input**: a 2d array with integers in increasing order.

```
[[0 1 2 3]
 [4 5 6 7]]
```
 
**Output**: Print the shape of the array.

```
(2, 4)
```


In [ ]:
# Given code
A = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7]])

# your code here


----
### Goal: Reshape an array.

A NumPy array's [`.reshape()` method](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.reshape.html#numpy.ndarray.reshape) takes the values in the array and rearranges them. The part that takes some getting used to is which values go in which new positions.

The [`np.arange()` function](https://numpy.org/doc/stable/reference/generated/numpy.arange.html) creates arrays with integers in increasing order. For example, the array `[0 1 2 3 4 5 6 7]` from the previous exercises can also be generated by the line `np.arange(8)`.


<span style="color:blue">**Exercise A13.**</span>

**Input**: an array with integers in increasing order.

```
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
```
 
**Output**: Create a new array with the same elements in two rows of equal size. Print the resulting array.

```
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
```


In [ ]:
# Given code
A = np.arange(16)

# your code here


----
### Goal: Get the number of elements in an array.

<span style="color:blue">**Exercise A14.**</span>

**Input**: Three arrays of different shapes with integers in increasing order.

```
A = [0 1 2 3 4 5 6 7]

B = [[0 1 2 3 4 5 6 7]]

C = [[0 1 2 3]
     [4 5 6 7]]
```
 
**Output**: Use an array's [`.size` attribute](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.size.html) to print the number of elements in each array.

```
8
8
8
```


In [ ]:
# Given code
A = np.arange(8)
B = np.arange(8).reshape(1, 8)
C = np.arange(8).reshape(2, 4)

# your code here


----
### Goal: Get the Python type of NumPy arrays, and get the type of the elements held in a NumPy array.

You can get the type of a variable in Python with the built-in `type()` function. NumPy arrays are a single type that can hold elements of another type. For example, you could have an array of integers or an array of strings.

<span style="color:blue">**Exercise A15.**</span>

**Input**: a 2x4 array with integers in increasing order.

```
[[0 1 2 3]
 [4 5 6 7]]
```
 
**Output**: Print the Python type of the array by using Python's built-in `type()` function.

```
<class 'numpy.ndarray'>
```


In [ ]:
# Given code
A = np.arange(8).reshape((2, 4))

# your code here


----
<span style="color:blue">**Exercise A16.**</span>

**Input**: a 2x4 array with integers in increasing order.

```
[[0 1 2 3]
 [4 5 6 7]]
```
 
**Output**: Print the NumPy array's [`dtype` attribute](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.dtype.html) in order to see the type of elements that the array holds.

```
int64
```


In [ ]:
# Given code
A = np.arange(8).reshape((2, 4))

# your code here


----
<span style="color:blue">**Exercise A17.**</span>

**Input**: an array of strings.

```
['maple' 'london plane' 'beech' 'white oak']
```
 
**Output**: Print the Python type of the array.

```
<class 'numpy.ndarray'>
```


In [ ]:
# Given code
A = np.array(['maple', 'london plane', 'beech', 'white oak'])

# your code here


----
<span style="color:blue">**Exercise A18.**</span>

**Input**: an array of strings.

```
['maple' 'london plane' 'beech' 'white oak']
```
 
**Output**: Print the NumPy array's [`dtype` attribute](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.dtype.html).

```
<U12
```

(This is a string datatype, as described [here](https://numpy.org/doc/stable/reference/arrays.dtypes.html))


In [ ]:
# Given code
A = np.array(['maple', 'london plane', 'beech', 'white oak'])

# your code here


----
### Goal: Create an array. Understand the difference between `np.empty()` and `np.zeros()`.

The [`np.empty()` function](https://numpy.org/doc/stable/reference/generated/numpy.empty.html) creates an array with no guarantees on the values of elements inside it. If you want to use an array created in this way, you need to explicitly set the values.

The [`np.zeros()` function](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html) creates an array where every entry is 0. This is useful when you want to immediately use the values in the array, or if the default value of an entry should be 0.

<span style="color:blue">**Exercise A19.**</span>

**Input**: None.

 
**Output**: Create a 4x4 array using the [`np.empty()` function](https://numpy.org/doc/stable/reference/generated/numpy.empty.html). Print the array.

*Note: This is just a representative output. Due to the nature of `np.empty()`, you will have different output. That is expected.* 

```
[[0.0e+000 4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323 3.5e-323]
 [4.0e-323 4.4e-323 4.9e-323 5.4e-323]
 [5.9e-323 6.4e-323 6.9e-323 7.4e-323]]
```




In [ ]:
# your code here



<span style="color:blue">**Exercise A20.**</span>

**Input**: None.

 
**Output**: Create a 4x4 array using the [`np.zeros()` function](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html). Print the array.

```
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
```




In [ ]:
# your code here


<span style="color:blue">**Exercise A21.**</span>

Evenly spaced numbers are often useful for plotting.

**Input**: None.

 
**Output**: Create a 1d array of 10 equally spaced numbers between 0 and 1 (inclusive) using the [`np.linpace()` function](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html). Print the array.

```
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
```


In [ ]:
# your code here


<span style="color:blue">**Exercise A22.**</span>

**Input**: a Python list containing six integers.

```
[10, 8, 6, 4, 2, 0]
```
 
**Output**: Create a NumPy array from the list using the [`np.array()` function](https://numpy.org/doc/stable/reference/generated/numpy.array.html). Reshape the array to be 3x2. Print the array.

```
[[10  8]
 [ 6  4]
 [ 2  0]]
```


In [ ]:
l = [10, 8, 6, 4, 2, 0]

# your code here


<span style="color:blue">**Exercise A23.**</span>

The `np.array()` constructor accepts lists of lists as arguments.
For example, the line `np.array([[2, 3], [4, 5]])` yields the following 2d array:

```
[[2 3]
 [4 5]]
```

The first list becomes the first row, and the second becomes the second row.

**Input**: None.

**Output**: Create a NumPy array from a list of lists that looks like the following array. Print the array.

```
[[5 6]
 [7 8]]
```


In [ ]:
# your code here


<span style="color:blue">**Exercise A24.**</span>

**Input**: a Python list containing six integers.

```
list1 = [10, 8, 6, 4, 2, 0]
list2 = [11, 9, 7, 5, 3, 1]
```
 
**Output**: Create a 2x6 NumPy array from the lists, where the elements of `list1` are in the first row and the elements of `list2` are in the second row. Print the array.

```
[[10  8  6  4  2  0]
 [11  9  7  5  3  1]]
```


In [ ]:
list1 = [10, 8, 6, 4, 2, 0]
list2 = [11, 9, 7, 5, 3, 1]

# your code here


## B. Saving/loading arrays

### Goal: Load a NumPy array from a file.

<span style="color:blue">**Exercise B1.**</span>

**Input**: No code. A file named `exercise-load.npy` is in this directory.
 
**Output**: Load the array in the file `exercise-load.npy` file using the [`np.load()` function](https://numpy.org/doc/stable/reference/generated/numpy.load.html). Print the resulting array.

```
[[0 3 6]
 [1 4 7]
 [2 5 8]]
```


In [ ]:
# your code here


### Goal: Save a NumPy array to a file.

<span style="color:blue">**Exercise B2.**</span>

**Input**: a 6x6 array with integers in increasing order.

```
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
```
 
**Output**: Save the array in a `.npy` file using the [`np.save()` function](https://numpy.org/doc/stable/reference/generated/numpy.save.html). Load the file you created using `np.load()`. Print the resulting array.

```
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
```


In [ ]:
# Given code
A = np.arange(36).reshape((6, 6))

# your code here


## C. Indexing

### Goal: Get the value of a single entry in an array.


In order to get an element from an array, you *index* the array with the element's position along each dimension/axis. The positions are numbered starting at 0.

You can use square bracket syntax like with a Python list. Different dimensions are separated with commas.

You might find the [NumPy reference for indexing](https://numpy.org/doc/stable/user/basics.indexing.html#basics-indexing) helpful.

<span style="color:blue">**Exercise C1.**</span>

**Input**: a 3x8 array with integers in increasing order.

```
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
```
 
**Output**: Print the top-left entry in the array, which is the entry in the first row, first column.

```
0
```


In [ ]:
# Given code
A = np.arange(24).reshape((3, 8))

# your code here


----
<span style="color:blue">**Exercise C2.**</span>

**Input**: a 3x8 array with integers in increasing order.

```
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
```
 
**Output**: Print the entry in the second row, third column.

```
10
```


In [ ]:
# Given code
A = np.arange(24).reshape((3, 8))

# your code here


----
<span style="color:blue">**Exercise C3.**</span>

**Input**: a 3x8 array with integers in increasing order.

```
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
```
 
**Output**: Print the entry in the third row, second column.

```
17
```


In [ ]:
# Given code
A = np.arange(24).reshape((3, 8))

# your code here


----
<span style="color:blue">**Exercise C4.**</span>

**Input**: a 3x8 array with integers in increasing order.

```
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
```
 
**Output**: Print the entry `13` using indexing.

```
13
```


In [ ]:
# Given code
A = np.arange(24).reshape((3, 8))

# your code here


--------
<span style="color:blue">**Exercise C5.**</span>

**Input**: a 1d array of integers.

```
A = [0 1 2 3 4 5 6 7 8 9]
```
 
**Output**: Use negative indexing to print the last element of the array.

```
9
```


In [ ]:
# Given code
A = np.arange(10)
print(A)

# your code here


### Goal: Set the value of a single entry in an array.

You can set the value of an entry in an array using the same bracket syntax used for indexing.
For example, `A[i, j] = 1` sets the entry in row `i`, column `j` to 1.

<span style="color:blue">**Exercise C6.**</span>

**Input**: a 3x8 array with integers in increasing order.

```
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
```
 
**Output**: Set the entry in the second row, third column to 100. Print the array.

```
[[  0   1   2   3   4   5   6   7]
 [  8   9 100  11  12  13  14  15]
 [ 16  17  18  19  20  21  22  23]]
```


In [ ]:
# Given code
A = np.arange(24).reshape((3, 8))

# your code here


----
### Goal: Get and set the value of an entire row or column of a 2D array.

*Slicing* allows you to access multiple elements of an array at the same time. A slice is defined using a colon. For example:
- `A[:, 1]` prints all of the entries in column 1 of `A`.
- `A[0, :]` prints all of the entries in row 0 of `A`.
- `A[:, 1:3]` prints all of the entries in columns 1 (inclusive) to 3 (not inclusive) of `A` (i.e. columns 1 and 2).

Syntax is described [here](https://numpy.org/doc/stable/user/basics.indexing.html#slicing-and-striding).

<span style="color:blue">**Exercise C7.**</span>

**Input**: a 3x8 array with integers in increasing order.

```
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
```
 
**Output**: Print all of the entries in the fifth column.

```
[ 4 12 20]
```


In [ ]:
# Given code
A = np.arange(24).reshape((3, 8))

# your code here


--------
<span style="color:blue">**Exercise C8.**</span>

**Input**: a 3x8 array with integers in increasing order.

```
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
```
 
**Output**: Print all of the entries in the first row.

```
[0 1 2 3 4 5 6 7]
```


In [ ]:
# Given code
A = np.arange(24).reshape((3, 8))

# your code here


--------
<span style="color:blue">**Exercise C9.**</span>

**Input**: a 3x8 array with integers in increasing order.

```
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
```
 
**Output**: Set all of the entries in the bottom row to 1. Print the array.

```
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [ 1  1  1  1  1  1  1  1]]
```


In [ ]:
# Given code
A = np.arange(24).reshape((3, 8))

# your code here


----
### Goal: use slicing to access parts of an array 



<span style="color:blue">**Exercise C10.**</span>

**Input**: a 3x8 array with integers in increasing order.

```
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
```
 
**Output**: Create a 2x2 array that contains the four entries that are a) in the first two rows and b) in the second two columns. Print this array.

```
[[ 1  2]
 [ 9 10]]
```


In [ ]:
# Given code
A = np.arange(24).reshape((3, 8))

# your code here


--------
<span style="color:blue">**Exercise C11.**</span>

**Input**: a 1d array of integers.

```
A = [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
     24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
     48 49]
```
 
**Output**: Use slicing to print the first 20 elements of the array.

```
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
```


In [ ]:
# Given code
A = np.arange(50)

# your code here


--------
<span style="color:blue">**Exercise C12.**</span>

**Input**: a 1d array of integers.

```
A = [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
     24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
     48 49]
```
 
**Output**: Use slicing to print the thirty elements of the array from index 10 to index 39 (inclusive).

```
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39]
```


In [ ]:
# Given code
A = np.arange(50)

# your code here


--------
<span style="color:blue">**Exercise C13.**</span>

**Input**: a 1d array of integers.

```
A = [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
     24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
     48 49]
```
 
**Output**: Use negative indexing and slicing to print the last ten elements of the array.

```
[40 41 42 43 44 45 46 47 48 49]
```


In [ ]:
# Given code
A = np.arange(50)

# your code here



<span style="color:blue">**Exercise C14.**</span>

**Input**: a 3x8 array with integers in increasing order.

```
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
```
 
**Output**: Use slicing and negative indexing to print the last row of the array.

```
[16 17 18 19 20 21 22 23]
```


In [ ]:
# Given code
A = np.arange(24).reshape((3, 8))

# your code here


---
**Goal: Use slicing to print a subset of a large array.**

Sometimes using the built-in Python `print()` function doesn't print all the values of a large array.

<span style="color:blue">**Exercise C15.**</span>

**Input**: a 100x100 array with integers in increasing order.

```
[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]
```
 
**Output**: Use slicing to print the full tenth row of the array.

```
[1000 1001 1002 1003 1004 1005 1006 1007 1008 1009 1010 1011 1012 1013
 1014 1015 1016 1017 1018 1019 1020 1021 1022 1023 1024 1025 1026 1027
 1028 1029 1030 1031 1032 1033 1034 1035 1036 1037 1038 1039 1040 1041
 1042 1043 1044 1045 1046 1047 1048 1049 1050 1051 1052 1053 1054 1055
 1056 1057 1058 1059 1060 1061 1062 1063 1064 1065 1066 1067 1068 1069
 1070 1071 1072 1073 1074 1075 1076 1077 1078 1079 1080 1081 1082 1083
 1084 1085 1086 1087 1088 1089 1090 1091 1092 1093 1094 1095 1096 1097
 1098 1099]
```


In [ ]:
# Given code
A = np.arange(10000).reshape((100,100))

# your code here


----
### Goal: use boolean indexing to access specific elements 

*Boolean indexing*, also called *logical indexing*, allows you to select elements of an array that meet certain criteria. There is a general pattern of starting with an arry, creating a boolean array where `True` corresponds to elements that satisfy a predicate, and then passing this boolean array as an index back to the original array to select those elements.

The NumPy indexing reference contains a [section on boolean indexing](https://numpy.org/doc/stable/user/basics.indexing.html#boolean-array-indexing).


<span style="color:blue">**Exercise C16.**</span>

**Input**: a 6x6 array with integers in increasing order.

```
A = [[ 0  1  2  3  4  5]
     [ 6  7  8  9 10 11]
     [12 13 14 15 16 17]
     [18 19 20 21 22 23]
     [24 25 26 27 28 29]
     [30 31 32 33 34 35]]
```
 
**Output**: Create an 8x8 array called `B` which contains `True` if the corresponding entry in `A` is even and `False` otherwise. More concretely: a) `B[i, j] = True` if the integer in `A[i, j]` is even, and b) `B[i, j] = False` if the integer in `A[i, j]` is odd. Print `B` once you have created it. 
```
[[ True False  True False  True False]
 [ True False  True False  True False]
 [ True False  True False  True False]
 [ True False  True False  True False]
 [ True False  True False  True False]
 [ True False  True False  True False]]
```

*Hint:* the modulo operator in Python yields the remainder when dividing. For example, `4 % 2` yields 0 because 4 is even, and `5 % 2` yields 1 because 5 is odd. The expression `4 % 2 == 0` would therefore yield `True`, while `5 % 2 == 0` would yield `False`.


In [ ]:
# Given code
A = np.arange(36).reshape((6, 6))

# your code here


--------
<span style="color:blue">**Exercise C17.**</span>

**Input**: a 6x6 array with integers in increasing order.

```
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
```
 
**Output**: Print all the even entries of the array using one line of logical indexing.

```
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34]
```


In [ ]:
# Given code
A = np.arange(36).reshape((6, 6))

# your code here


--------
<span style="color:blue">**Exercise C18.**</span>

**Input**: a 6x6 array with integers in increasing order.

```
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
```
 
**Output**: Set all the odd entries of the array to 1 using one line of logical indexing. Print the resulting array.

```
[[ 0  1  2  1  4  1]
 [ 6  1  8  1 10  1]
 [12  1 14  1 16  1]
 [18  1 20  1 22  1]
 [24  1 26  1 28  1]
 [30  1 32  1 34  1]]
```


In [ ]:
# Given code
A = np.arange(36).reshape((6, 6))

# your code here


--------
<span style="color:blue">**Exercise C19.**</span>

**Input**: a 6x6 array with integers in increasing order.

```
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
```
 
**Output**: Set all the odd entries of the array to increasing integers starting from 100. The first odd number should become 100, the second should become 101, and so on with the final odd number becoming 117. Print the resulting array.

```
[[  0 100   2 101   4 102]
 [  6 103   8 104  10 105]
 [ 12 106  14 107  16 108]
 [ 18 109  20 110  22 111]
 [ 24 112  26 113  28 114]
 [ 30 115  32 116  34 117]]
```


In [ ]:
# Given code
A = np.arange(36).reshape((6, 6))

# your code here


--------
<span style="color:blue">**Exercise C20.**</span>

**Input**: a 6x6 array with integers in increasing order.

```
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
```
 
**Output**: Add 50 to all of the odd entries of the array. Print the resulting array.

```
[[ 0 51  2 53  4 55]
 [ 6 57  8 59 10 61]
 [12 63 14 65 16 67]
 [18 69 20 71 22 73]
 [24 75 26 77 28 79]
 [30 81 32 83 34 85]]
```


In [ ]:
# Given code
A = np.arange(36).reshape((6, 6))

# your code here


## D. Operating on arrays

*Broadcasting* refers to treating a value or a smaller array as a larger array. It is a convenient way to operate on arrays without writing `for` loops or explicitly constructing larger arrays.

You might find the [NumPy reference for broadcasting](https://numpy.org/doc/stable/user/basics.broadcasting.html) helpful

### Goal: use broadcasting to set array elements.

<span style="color:blue">**Exercise D1.**</span>

**Input**: a 3x8 array with integers in increasing order.

```
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
```
 
**Output**: Set all of the entries in the array to be one using a call to `np.ones()`. Print the array.

```
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
```


In [ ]:
# Given code
A = np.arange(24).reshape((3, 8))

# your code here


--------
<span style="color:blue">**Exercise D2.**</span>

**Input**: a 3x8 array with integers in increasing order.

```
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
```
 
**Output**: Set all of the entries in the array to 1 using broadcasting. You will likely need to use two colon slices. Print the array.

```
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
```


In [ ]:
# Given code
A = np.arange(24).reshape((3, 8))

# your code here


--------
<span style="color:blue">**Exercise D3.**</span>

**Input**: a 3x8 array with integers in increasing order.

```
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
```
 
**Output**: Add 20 to all the elements of the array using broadcasting. Print the array.

```
[[20 21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43]]
```


In [ ]:
# Given code
A = np.arange(24).reshape((3, 8))

# your code here


----
### Goal: Operate on specific axes of an array.

Some built-in NumPy functions have an `axis` argument that determines how the function is applied. For example, specifying a value for the `axis` argument lets the function operate only on rows or only on columns.

<span style="color:blue">**Exercise D4.**</span>

**Input**: a 2x6 array with integers in increasing order.

```
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
```
 
**Output**: Use the [`np.mean()` function](https://numpy.org/doc/stable/reference/generated/numpy.mean.html) to print the mean of all of the elements in the array.

```
5.5
```


In [ ]:
# Given code
A = np.arange(12).reshape((2, 6))

# your code here


--------
<span style="color:blue">**Exercise D5.**</span>

**Input**: a 2x6 array with integers in increasing order.

```
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
```
 
**Output**: Use `np.mean()` to print the mean of each of the columns of the array.

```
[3. 4. 5. 6. 7. 8.]
```


In [ ]:
# Given code
A = np.arange(12).reshape((2, 6))

# your code here


--------
<span style="color:blue">**Exercise D6.**</span>

**Input**: a 2x6 array with integers in increasing order.

```
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
```
 
**Output**: Use `np.mean()` to print the mean of each of the columns of the array.

```
[2.5 8.5]
```


In [ ]:
# Given code
A = np.arange(12).reshape((2, 6))

# your code here


--------
<span style="color:blue">**Exercise D7.**</span> Normalizing by a single value.

**Input**: a 2x6 array with integers in increasing order.

```
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
```
 
**Output**: Normalize each entry in the array by the overall mean of the array's elements. Each element will be divided by 5.5 in this example:

```
[[0.         0.18181818 0.36363636 0.54545455 0.72727273 0.90909091]
 [1.09090909 1.27272727 1.45454545 1.63636364 1.81818182 2.        ]]
```


In [ ]:
# Given code
A = np.arange(12).reshape((2, 6))

# your code here


--------
<span style="color:blue">**Exercise D8.**</span> Normalizing by a different value for each column.

**Input**: a 2x6 array with integers in increasing order.

```
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
```
 
**Output**: Normalize each entry by the mean of that entry's column. For example, `0` will be divided by `3` (the mean of `0` and `6`).

```
[[0.         0.25       0.4        0.5        0.57142857 0.625     ]
 [2.         1.75       1.6        1.5        1.42857143 1.375     ]]
```


In [ ]:
# Given code
A = np.arange(12).reshape((2, 6))

# your code here


--------
<span style="color:blue">**Exercise D9.**</span> Turning a column into a percentage.

**Input**: a 2x6 array with integers in increasing order.

```
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
```
 
**Output**: Normalize each entry by the sum of that entry's column. For example, `1` will be divided by `8` (the sum of `1` and `7`).

```
[[0.         0.125      0.2        0.25       0.28571429 0.3125    ]
 [1.         0.875      0.8        0.75       0.71428571 0.6875    ]]
```


In [ ]:
# Given code
A = np.arange(12).reshape((2, 6))

# your code here


--------
<span style="color:blue">**Exercise D10.**</span> Turning a row into a percentage. This can be tricky because using the previous strategy will result in a broadcasting shape error.

**Input**: a 2x6 array with integers in increasing order.

```
A = [[ 0  1  2  3  4  5]
     [ 6  7  8  9 10 11]]
```
 
**Output**:

Part a: Store the sum of the entries in each row in a new array. Print this array.

```
[15 51]
```

Part b: Use `np.newaxis` to add a new dimension to the array of row sums. The resulting array will have a 6x1 shape. Print this array.

```
[[15]
 [51]]
```

Part c: Normalize each entry in the original array `A` by the sum of that entry's row. For example, `0` will be divided by `15` (the sum of the first row).

```
[[0.         0.06666667 0.13333333 0.2        0.26666667 0.33333333]
 [0.11764706 0.1372549  0.15686275 0.17647059 0.19607843 0.21568627]]
```


In [ ]:
# Given code
A = np.arange(12).reshape((2, 6))

# part a. your code here


# part b. your code here


# part c. your code here


## E. Avoiding `for` loops

NumPy offers many shorter (though often initially more confusing) ways of operating on arrays than explicitly writing `for` loops.

<span style="color:blue">**Exercise E1.**</span> Adding 2 arrays.

**Input**: two 2x6 arrays of integers in increasing order.

```
A = [[ 0  1  2  3  4  5]
     [ 6  7  8  9 10 11]]
     
B = [[ 100  101  102  103  104  105]
     [ 106  107  108  109  110  111]]
```
 
**Output**: Rewrite the existing code that uses a for loop to add the two arrays to use only one-line of built-in NumPy arithmetic. Print the resulting array.

```
[[100 102 104 106 108 110]
 [112 114 116 118 120 122]]
```


In [ ]:
# Given code
A = np.arange(12).reshape((2, 6))
B = np.arange(100, 112).reshape((2, 6))

# for loop version
C = np.empty((2,6))
for i in range(A.shape[0]):
    for j in range(B.shape[1]):
        C[i, j] = A[i, j] + B[i, j]

# your code here
